version: '3'

service:
  server:
    build: ./server
    links: 
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: root

  client:
    build: ./client
    links:  
      - server
    ports:
      - 8000:8000

  mysql:
    build: ./mysql
    command: -default-authentication-plugin=mysql_native_passwoed
    restart: always
